// Builds data/refresh-2026.js and research/copy-refresh-log.md from the
// per-league fact-refresh files in research/raw/refresh-<league>.json.
// Run: node scripts/build-refresh.mjs

import fs from 'fs'
import path from 'path'

const ROOT = path.resolve(path.dirname(new URL(import.meta.url).pathname.replace(/^\/([A-Z]:)/, '$1')), '..')
const RAW = path.join(ROOT, 'research', 'raw')
const LEAGUES = ['nfl', 'nba', 'mlb', 'nhl', 'mls', 'epl']
// Strips em/en dashes from strings, recursively through objects and arrays.
const noDash = (v) => {
  if (typeof v === 'string') return v.replace(/\s*[–—]\s*/g, ', ')
  if (Array.isArray(v)) return v.map(noDash)
  if (v && typeof v === 'object') return Object.fromEntries(Object.entries(v).map(([k, x]) => [k, noDash(x)]))
  return v
}
const HEDGES = /\b(perhaps|might|arguably|possibly|could be|may be)\b/i

const overlay = {}
const log = []
const stats = { teams: 0, changes: 0, notes: 0, unverified: 0, hedged: [] }

for (const l of LEAGUES) {
  const f = path.join(RAW, `refresh-${l}.json`)
  if (!fs.existsSync(f)) { log.push(`## ${l.toUpperCase()}\n\n_No refresh file yet._\n`); continue }
  let rows
  try { rows = JSON.parse(fs.readFileSync(f, 'utf8')) } catch (e) { log.push(`## ${l.toUpperCase()}\n\n_refresh-${l}.json failed to parse: ${e.message}_\n`); continue }
  log.push(`## ${l.toUpperCase()} (${rows.length} teams)\n`)
  for (const r of rows) {
    if (!r.teamId) continue
    stats.teams++
    const changes = (r.changes ?? []).filter((c) => c.field && c.new !== undefined && JSON.stringify(c.new) !== JSON.stringify(c.old))
      .map((c) => ({ ...c, new: noDash(c.new) }))
    const notes = noDash(r.analystNotes) || null
    if (notes && HEDGES.test(notes)) stats.hedged.push(r.teamId)
    overlay[r.teamId] = { asOf: r.asOf ?? '2026-09', changes, analystNotes: notes }
    stats.changes += changes.length
    if (notes) stats.notes++
    stats.unverified += (r.unverified ?? []).length

    log.push(`### ${r.team ?? r.teamId}`)
    if (notes) log.push(`- **Overview rewritten.** Basis: ${noDash(r.analystNotesBasis) || 'current Forbes figures'}`)
    for (const c of changes) {
      log.push(`- \`${c.field}\`: ${fmt(c.old)} → ${fmt(c.new)}. ${noDash(c.fact) || ''}${c.source ? ` [source](${c.source})` : ''}`)
    }
    if (!changes.length) log.push(`- No factual changes; ${notes ? 'overview regenerated against current numbers' : 'overview unchanged'}.`)
    for (const u of r.unverified ?? []) log.push(`- Unverified: ${noDash(u)}`)
    log.push('')
  }
}

function fmt(v) {
  if (v == null) return 'null'
  const s = typeof v === 'string' ? v : JSON.stringify(v)
  return s.length > 90 ? `"${s.slice(0, 87)}..."` : typeof v === 'string' ? `"${s}"` : s
}

fs.writeFileSync(
  path.join(ROOT, 'data', 'refresh-2026.js'),
  `// GENERATED by scripts/build-refresh.mjs from research/raw/refresh-*.json.\n` +
    `// Fact refresh overlay applied in enrichments.js: dot-path field changes and\n` +
    `// rewritten analystNotes verified as of September 2026.\n` +
    `export const refresh2026 = ${JSON.stringify(overlay, null, 2)}\n`
)

const head = [
  '# Copy refresh log',
  '',
  `Generated ${new Date().toISOString().slice(0, 10)} by \`scripts/build-refresh.mjs\`. Every team overview (analystNotes) rewritten and every fact changed in the September 2026 refresh, with the fact that changed it. Applied as an overlay in \`data/enrichments.js\`; the original enrichment files are untouched.`,
  '',
  `Totals: ${stats.teams} teams, ${stats.notes} overviews rewritten, ${stats.changes} field changes, ${stats.unverified} items left unverified.`,
  '',
]
fs.writeFileSync(path.join(ROOT, 'research', 'copy-refresh-log.md'), [...head, ...log].join('\n') + '\n')
console.log(`refresh overlay: ${stats.teams} teams, ${stats.notes} notes, ${stats.changes} changes, ${stats.unverified} unverified`)
if (stats.hedged.length) console.log('hedged wording in:', stats.hedged.join(', '))
