// Builds data/forbes-proxies.js from research/raw/proxies-*.json.
// Observable proxies for the Forbes-breakdown sanity models (never Forbes data).
// Run: node scripts/build-proxies.mjs

import fs from 'fs'
import path from 'path'
import { pathToFileURL } from 'url'

const ROOT = path.resolve(path.dirname(new URL(import.meta.url).pathname.replace(/^\/([A-Z]:)/, '$1')), '..')
const RAW = path.join(ROOT, 'research', 'raw')
const read = (f) => (fs.existsSync(path.join(RAW, f)) ? JSON.parse(fs.readFileSync(path.join(RAW, f), 'utf8')) : null)
const num = (v) => (typeof v === 'number' && Number.isFinite(v) ? v : null)
// Public copy: no dashes, and drop research caveats ("not asserted here") from notes.
const clean = (s) => (typeof s === 'string'
  ? s.replace(/\s*[–—]\s*/g, ', ')
      .split(/(?<=\.)\s+/).filter((x) => !/not asserted|not officially published|not published/i.test(x)).join(' ').trim() || null
  : s)

const proxies = {}
const get = (id) => (proxies[id] ||= {})

// Market (one record per metro). competitors = other big-four teams in the metro.
for (const m of read('proxies-market.json') ?? []) {
  const ids = m.teamIds ?? []
  for (const id of ids) {
    Object.assign(get(id), {
      metro: m.metro,
      pop: num(m.cbsaPopulation),
      tvh: num(m.tvHouseholds),
      income: num(m.medianHouseholdIncome),
      competitors: ids.length - 1,
    })
  }
}

for (const f of ['proxies-nfl-nba.json', 'proxies-mlb-nhl.json']) {
  const j = read(f)
  if (!j) continue
  for (const s of j.stadium ?? []) {
    Object.assign(get(s.teamId), {
      venue: s.venue ?? null,
      yearOpened: num(s.yearOpened),
      yearRenovated: num(s.yearRenovated),
      capacity: num(s.capacity),
      premiumSeats: num(s.premiumSeats) ?? (num(s.suites) != null && num(s.clubSeats) != null ? s.suites + s.clubSeats : null),
      suites: num(s.suites),
      teamOwned: s.ownership == null ? null : s.ownership === 'team' || s.teamControlsRevenue === true,
      eventRevenueM: num(s.nonLeagueEventRevenueM),
    })
  }
  for (const b of j.brand ?? []) {
    Object.assign(get(b.teamId), {
      titles25: num(b.championships25y),
      // Canadian NHL clubs: national exposure is Sportsnet/CBC, not ESPN/TNT.
      nationalTv: num(b.nationalTvGamesCanada) ?? num(b.nationalTvGames),
      nationalTvScope: num(b.nationalTvGamesCanada) != null ? 'Canada' : 'US',
      socialM: num(b.socialFollowers),
      merchRank: num(b.merchRank),
    })
  }
  for (const n of j.sportNotes ?? []) {
    if (n.note) get(n.teamId).sportNote = clean(n.note)
  }
}

// Stadium extras from the site's own researched enrichments: land ownership,
// naming-rights value, and whether the team controls adjacent real estate.
const slug = (n) => n.toLowerCase().normalize('NFD').replace(/[̀-ͯ]/g, '')
  .replace(/&/g, 'and').replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '')
const parseNaming = (d) => {
  if (!d) return null
  if (typeof d === 'object') return num(d.annualValue_M)
  const m = d.match(/\$(\d+(?:\.\d+)?)(?:\s*[-–]\s*\$?(\d+(?:\.\d+)?))?\s*M\s*(?:\/|per\s+)(?:year|yr)/i)
  if (!m) return null
  return m[2] ? (parseFloat(m[1]) + parseFloat(m[2])) / 2 : parseFloat(m[1])
}
const DISTRICT_RE = /mixed-use|entertainment district|stadium district|ballpark village|\bacres?\b|real[- ]estate|development rights|surrounding (?:land|property|development)|\bdistrict\b/i
for (const l of ['nfl', 'nba', 'mlb', 'nhl']) {
  const mod = await import(pathToFileURL(path.join(ROOT, 'data', `enrichments-${l}.js`)).href)
  for (const [name, e] of Object.entries(Object.values(mod)[0])) {
    const id = slug(name)
    if (!proxies[id]) continue
    const v = e.stadium || e.arena || {}
    const text = [v.ownershipModel, v.nonGameRevenue, v.nonArenaRevenue, v.newStadiumPlans, v.newArenaPlans, e.analystNotes].filter(Boolean).join(' ')
    Object.assign(proxies[id], {
      teamOwnsLand: typeof v.teamOwnsLand === 'boolean' ? v.teamOwnsLand : null,
      namingRightsAnnualM: parseNaming(v.namingRightsDeal),
      namingRightsSponsor: typeof v.namingRightsDeal === 'object' ? v.namingRightsDeal?.sponsor ?? null
        : typeof v.namingRightsDeal === 'string' ? v.namingRightsDeal.split(',')[0].trim() : null,
      // true when the team's own entity controls adjacent land or a development district
      realEstateDistrict: DISTRICT_RE.test(text) && (v.teamOwnsLand === true || /team[- ]owned|owned by the team|owns the .{0,40}(land|district|acres)|team-controlled/i.test(text)),
      publicSubsidyM: num(v.publicSubsidy),
      privateFinancingM: num(v.privateFinancing),
    })
  }
}

fs.writeFileSync(
  path.join(ROOT, 'data', 'forbes-proxies.js'),
  `// GENERATED by scripts/build-proxies.mjs from research/raw/proxies-*.json.\n` +
    `// Observable proxies (Census, Nielsen, venue and league sources) used to sanity-check\n` +
    `// Forbes' component values. Sources per field live in the raw research files.\n` +
    `export const forbesProxies = ${JSON.stringify(proxies, null, 2)}\n`
)
console.log(`proxies for ${Object.keys(proxies).length} teams`)
