// Builds data/forbes-proxies.js from research/raw/proxies-*.json.
// Observable proxies for the Forbes-breakdown sanity models (never Forbes data).
// Run: node scripts/build-proxies.mjs

import fs from 'fs'
import path from 'path'

const ROOT = path.resolve(path.dirname(new URL(import.meta.url).pathname.replace(/^\/([A-Z]:)/, '$1')), '..')
const RAW = path.join(ROOT, 'research', 'raw')
const read = (f) => (fs.existsSync(path.join(RAW, f)) ? JSON.parse(fs.readFileSync(path.join(RAW, f), 'utf8')) : null)
const num = (v) => (typeof v === 'number' && Number.isFinite(v) ? v : null)
const clean = (s) => (typeof s === 'string' ? s.replace(/\s*[–—]\s*/g, ', ') : s)

const proxies = {}
const get = (id) => (proxies[id] ||= {})

// Market (one record per metro). competitors = other big-four teams in the metro.
for (const m of read('proxies-market.json') ?? []) {
  const ids = m.teamIds ?? []
  for (const id of ids) {
    Object.assign(get(id), {
      metro: m.metro,
      pop: num(m.cbsaPopulation),
      tvh: num(m.tvHouseholds),
      income: num(m.medianHouseholdIncome),
      competitors: ids.length - 1,
    })
  }
}

for (const f of ['proxies-nfl-nba.json', 'proxies-mlb-nhl.json']) {
  const j = read(f)
  if (!j) continue
  for (const s of j.stadium ?? []) {
    Object.assign(get(s.teamId), {
      venue: s.venue ?? null,
      yearOpened: num(s.yearOpened),
      yearRenovated: num(s.yearRenovated),
      capacity: num(s.capacity),
      premiumSeats: num(s.premiumSeats) ?? (num(s.suites) != null && num(s.clubSeats) != null ? s.suites + s.clubSeats : null),
      suites: num(s.suites),
      teamOwned: s.ownership == null ? null : s.ownership === 'team' || s.teamControlsRevenue === true,
      eventRevenueM: num(s.nonLeagueEventRevenueM),
    })
  }
  for (const b of j.brand ?? []) {
    Object.assign(get(b.teamId), {
      titles25: num(b.championships25y),
      nationalTv: num(b.nationalTvGames),
      socialM: num(b.socialFollowers),
      merchRank: num(b.merchRank),
    })
  }
  for (const n of j.sportNotes ?? []) {
    if (n.note) get(n.teamId).sportNote = clean(n.note)
  }
}

fs.writeFileSync(
  path.join(ROOT, 'data', 'forbes-proxies.js'),
  `// GENERATED by scripts/build-proxies.mjs from research/raw/proxies-*.json.\n` +
    `// Observable proxies (Census, Nielsen, venue and league sources) used to sanity-check\n` +
    `// Forbes' component values. Sources per field live in the raw research files.\n` +
    `export const forbesProxies = ${JSON.stringify(proxies, null, 2)}\n`
)
console.log(`proxies for ${Object.keys(proxies).length} teams`)
